name: AppleClang
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      platform_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      std_version:
        required: true
        type: string
      cmake_args:
        required: false
        type: string
        default: ""
      ctest_args:
        required: false
        type: string
        default: ""
      build_type:
        required: false
        type: string
        default: "Debug"
env:
  BUILD_TYPE: ${{inputs.build_type}}
jobs:
  build:
    name: ${{inputs.name}}
    runs-on: ${{inputs.image_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake (${{inputs.platform_name}})
        run: >-
          cmake -B ${{github.workspace}}/build-${{inputs.platform_name}}-cpp${{inputs.std_version}}
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_CXX_STANDARD=${{inputs.std_version}}
          ${{inputs.cmake_args}}
      - name: Build (${{inputs.platform_name}})
        run: >-
          export NUM_THREADS=$(sysctl -n hw.ncpu)
          && echo "Building with $NUM_THREADS threads"
          && cmake --build ${{github.workspace}}/build-${{inputs.platform_name}}-cpp${{inputs.std_version}}
          --config ${{env.BUILD_TYPE}}
          --parallel $NUM_THREADS
      - name: Test (${{inputs.platform_name}})
        working-directory: ${{github.workspace}}/build-${{inputs.platform_name}}-cpp${{inputs.std_version}}
        run: ctest -C ${{env.BUILD_TYPE}} ${{inputs.ctest_args}}
