name: Clang
on:
  workflow_call:
    inputs:
      name: 
        required: true
        type: string
      platform_name:
        required: true
        type: string
      std_version:
        required: true
        type: string
      version:
        required: true
        type: string
      cmake_args:
        required: false
        type: string
        default: ""
      ctest_args:
        required: false
        type: string
        default: ""
      build_type:
        required: false
        type: string
        default: "Debug"
env:
  BUILD_TYPE: ${{inputs.build_type}}
jobs:
  build:
    name: ${{inputs.name}}
    runs-on: ["riscv64"]
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Submodules
        run: git submodule update --init
      - name: Configure CMake (${{inputs.platform_name}})
        run: >-
          cmake -B ${{github.workspace}}/build-${{inputs.platform_name}}-clang-cpp${{inputs.std_version}}
          -DCMAKE_CXX_FLAGS=-stdlib=libc++
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DGTEST_USE_OWN_TR1_TUPLE=1
          -DCMAKE_CXX_STANDARD=${{inputs.std_version}}
          ${{inputs.cmake_args}}
      - name: Build (${{inputs.platform_name}})
        run: >-
          cmake --build ${{github.workspace}}/build-${{inputs.platform_name}}-clang-cpp${{inputs.std_version}}
          --config ${{env.BUILD_TYPE}}
          --clean-first
      - name: Test (${{inputs.platform_name}})
        working-directory: ${{github.workspace}}/build-${{inputs.platform_name}}-clang-cpp${{inputs.std_version}}
        run: ctest -C ${{env.BUILD_TYPE}} ${{inputs.ctest_args}}