name: C++ Quick
on:
  workflow_call:
    inputs:
      cmake_args:
        required: false
        type: string
        default: ""
      ctest_args:
        required: false
        type: string
        default: ""
      build_type:
        required: false
        type: string
        default: "Debug"
      std_version:
        required: false
        type: string
        default: 20
jobs:
  # Linux
  ubuntu-22-04-gcc:
    name: Ubuntu 22.04 (GCC)
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      platform_name: ubuntu-22
      image_name: ubuntu-22.04
      std_version: ${{inputs.std_version}}
      version: 12
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  # macOS
  macos-13:
    name: macOS 13 (AppleClang)
    uses: karmakrafts/workflows/.github/workflows/clang-macos.yml@master
    with:
      platform_name: macos-13
      image_name: macos-13
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  # Windows
  windows-2022-msvc:
    name: Windows 2022 (MSVC)
    uses: karmakrafts/workflows/.github/workflows/msvc.yml@master
    with:
      platform_name: windows-2022
      image_name: windows-2022
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}
