name: Build & Test
on:
  workflow_call:
    inputs:
      cmake_args:
        required: false
        type: string
        default: ""
      ctest_args:
        required: false
        type: string
        default: ""
      build_type:
        required: false
        type: string
        default: "Debug"
jobs:
  # Linux
  ubuntu-20-04-cpp17-gcc:
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      platform_name: ubuntu-20
      image_name: ubuntu-20.04
      std_version: 17
      version: 11
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-20-04-cpp20-gcc:
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      platform_name: ubuntu-20
      image_name: ubuntu-20.04
      std_version: 20
      version: 11
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-20-04-cpp17-clang:
    uses: karmakrafts/workflows/.github/workflows/clang.yml@master
    with:
      platform_name: ubuntu-20
      image_name: ubuntu-20.04
      std_version: 17
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-20-04-cpp20-clang:
    uses: karmakrafts/workflows/.github/workflows/clang.yml@master
    with:
      platform_name: ubuntu-20
      image_name: ubuntu-20.04
      std_version: 20
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-22-04-cpp17-gcc:
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      platform_name: ubuntu-22
      image_name: ubuntu-22.04
      std_version: 17
      version: 12
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-22-04-cpp20-gcc:
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      platform_name: ubuntu-22
      image_name: ubuntu-22.04
      std_version: 20
      version: 12
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-22-04-cpp17-clang:
    uses: karmakrafts/workflows/.github/workflows/clang.yml@master
    with:
      platform_name: ubuntu-22
      image_name: ubuntu-22.04
      std_version: 17
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-22-04-cpp20-clang:
    uses: karmakrafts/workflows/.github/workflows/clang.yml@master
    with:
      platform_name: ubuntu-22
      image_name: ubuntu-22.04
      std_version: 20
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  # MacOS
  macos-11-cpp17:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-11
      image_name: macos-11
      std_version: 17
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  macos-11-cpp20:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-11
      image_name: macos-11
      std_version: 20
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  macos-12-cpp17:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-12
      image_name: macos-12
      std_version: 17
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  macos-12-cpp20:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-12
      image_name: macos-12
      std_version: 20
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  macos-13-cpp17:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-13
      image_name: macos-13
      std_version: 17
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  macos-13-cpp20:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-13
      image_name: macos-13
      std_version: 20
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  # Windows
  windows-2019-cpp17-msvc:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: windows-2019
      image_name: windows-2019
      std_version: 17
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2019-cpp20-msvc:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: windows-2019
      image_name: windows-2019
      std_version: 20
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2019-cpp17-clang:
    uses: karmakrafts/workflows/.github/workflows/clang-windows.yml@master
    with:
      platform_name: windows-2019
      image_name: windows-2019
      std_version: 17
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2019-cpp20-clang:
    uses: karmakrafts/workflows/.github/workflows/clang-windows.yml@master
    with:
      platform_name: windows-2019
      image_name: windows-2019
      std_version: 20
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  windows-2022-cpp17-msvc:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: windows-2022
      image_name: windows-2022
      std_version: 17
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2022-cpp20-msvc:
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: windows-2022
      image_name: windows-2022
      std_version: 20
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2022-cpp17-clang:
    uses: karmakrafts/workflows/.github/workflows/clang-windows.yml@master
    with:
      platform_name: windows-2022
      image_name: windows-2022
      std_version: 17
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2022-cpp20-clang:
    uses: karmakrafts/workflows/.github/workflows/clang-windows.yml@master
    with:
      platform_name: windows-2022
      image_name: windows-2022
      std_version: 20
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}