name: C++
on:
  workflow_call:
    inputs:
      cmake_args:
        required: false
        type: string
        default: ""
      ctest_args:
        required: false
        type: string
        default: ""
      build_type:
        required: false
        type: string
        default: "Debug"
      std_version:
        required: false
        type: string
        default: 20
jobs:
  # Linux
  linux-x64-gcc:
    name: Linux x64/GCC
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      name: Linux x64/GCC
      platform_name: linux-x64-gcc
      image_name: ubuntu-22.04
      std_version: ${{inputs.std_version}}
      version: 12
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  linux-x64-clang:
    name: Linux x64/Clang
    uses: karmakrafts/workflows/.github/workflows/clang.yml@master
    with:
      name: Linux x64/Clang
      platform_name: linux-x64-clang
      image_name: ubuntu-22.04
      std_version: ${{inputs.std_version}}
      version: 17
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  linux-arm64-clang:
    name: Linux arm64/Clang
    uses: karmakrafts/workflows/.github/workflows/clang-pi.yml@master
    with:
      name: Linux arm64/Clang
      platform_name: linux-arm64-clang
      std_version: ${{inputs.std_version}}
      version: 17
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  linux-riscv64-clang:
    name: Linux riscv64/Clang
    uses: karmakrafts/workflows/.github/workflows/clang-starfive.yml@master
    with:
      name: Linux riscv64/Clang
      platform_name: linux-riscv64-clang
      std_version: ${{inputs.std_version}}
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  # MacOS
  macos-x64-clang:
    name: macOS x64/Clang
    uses: karmakrafts/workflows/.github/workflows/clang-macos.yml@master
    with:
      name: macOS x64/Clang
      platform_name: macos-x64-clang
      image_name: macos-13
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  # Windows
  windows-x64-msvc:
    name: Windows x64/MSVC
    uses: karmakrafts/workflows/.github/workflows/msvc.yml@master
    with:
      name: Windows x64/MSVC
      platform_name: windows-x64-msvc
      image_name: windows-2022
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-x64-clang:
    name: Windows x64/Clang
    uses: karmakrafts/workflows/.github/workflows/clang-windows.yml@master
    with:
      name: Windows x64/Clang
      platform_name: windows-x64-clang
      image_name: windows-2022
      std_version: ${{inputs.std_version}}
      version: 16
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
