name: C++
on:
  workflow_call:
    inputs:
      cmake_args:
        required: false
        type: string
        default: ""
      ctest_args:
        required: false
        type: string
        default: ""
      build_type:
        required: false
        type: string
        default: "Debug"
      std_version:
        required: false
        type: string
        default: 20
jobs:
  # Linux
  ubuntu-20-04-gcc:
    name: Ubuntu 20.04 (GCC)
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      platform_name: ubuntu-20
      image_name: ubuntu-20.04
      std_version: ${{inputs.std_version}}
      version: 11
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-20-04-clang:
    name: Ubuntu 20.04 (Clang)
    uses: karmakrafts/workflows/.github/workflows/clang.yml@master
    with:
      platform_name: ubuntu-20
      image_name: ubuntu-20.04
      std_version: ${{inputs.std_version}}
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  ubuntu-22-04-gcc:
    name: Ubuntu 22.04 (GCC)
    uses: karmakrafts/workflows/.github/workflows/gcc.yml@master
    with:
      platform_name: ubuntu-22
      image_name: ubuntu-22.04
      std_version: ${{inputs.std_version}}
      version: 12
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  ubuntu-22-04-clang:
    name: Ubuntu 22.04 (Clang)
    uses: karmakrafts/workflows/.github/workflows/clang.yml@master
    with:
      platform_name: ubuntu-22
      image_name: ubuntu-22.04
      std_version: ${{inputs.std_version}}
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  # MacOS
  macos-11:
    name: macOS 11 (AppleClang)
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-11
      image_name: macos-11
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  macos-12:
    name: macOS 12 (AppleClang)
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-12
      image_name: macos-12
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  macos-13:
    name: macOS 13 (AppleClang)
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: macos-13
      image_name: macos-13
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  # Windows
  windows-2019-msvc:
    name: Windows 2019 (MSVC)
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: windows-2019
      image_name: windows-2019
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2019-clang:
    name: Windows 2019 (Clang)
    uses: karmakrafts/workflows/.github/workflows/clang-windows.yml@master
    with:
      platform_name: windows-2019
      image_name: windows-2019
      std_version: ${{inputs.std_version}}
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}

  windows-2022-msvc:
    name: Windows 2022 (MSVC)
    uses: karmakrafts/workflows/.github/workflows/default.yml@master
    with:
      platform_name: windows-2022
      image_name: windows-2022
      std_version: ${{inputs.std_version}}
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}
  windows-2022-clang:
    name: Windows 2022 (Clang)
    uses: karmakrafts/workflows/.github/workflows/clang-windows.yml@master
    with:
      platform_name: windows-2022
      image_name: windows-2022
      std_version: ${{inputs.std_version}}
      version: 15
      cmake_args: ${{inputs.cmake_args}}
      ctest_args: ${{inputs.ctest_args}}
      build_type: ${{inputs.build_type}}